version: '3.8'

services:
  ai-travel-planner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: ai-travel-planner
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge
